apiVersion: v1
kind: Service
metadata:
  name: {{ template "masterreplica.fullname" . }}-0
  #namespace: masterreplica
  labels:
    name: {{ template "masterreplica.fullname" . }}-0
spec:
  ports:
  - port: 3306
    name: mariadb
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "masterreplica.fullname" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "masterreplica.fullname" . }}-1
  #namespace: masterreplica
  labels:
    name: {{ template "masterreplica.fullname" . }}-1
spec:
  ports:
  - port: 3306
    name: mariadb
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "masterreplica.fullname" . }}-1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "masterreplica.fullname" . }}-2
  #namespace: masterreplica
  labels:
    name: {{ template "masterreplica.fullname" . }}-2
spec:
  ports:
  - port: 3306
    name: mariadb
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "masterreplica.fullname" . }}-2
