{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "phpapp.fullname" . }}-secrets
  labels: {{- include "phpapp.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_USER: TUFSSUFEQl9VU0VS
  MARIADB_USER_PASSWORD: bWFyaWFkYg==
  MARIADB_HOST: cndzcGxpdC5tYXJpYWRiLWtlc3Rlci5zdmMuY2x1c3Rlci5sb2NhbA==
  MARIADB_DB: ZW1wbG95ZWVz
{{- end }}
