apiVersion: v1
kind: Service
metadata:
  name: {{ template "phpapp.fullname" . }}
  labels: {{- include "phpapp.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
  selector:
    app: phpapp