apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpadmin
spec:
  selector:
    matchLabels:
      app: phpapp
  replicas: 2
  serviceName: {{ template "phpapp.fullname" . }}
  template:
    metadata:
      labels:
        app: phpadmin
    spec:
      containers:
      - name: mariadb
        image: {{ template "phpapp.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "phpapp.fullname" . }}-secrets
              key: MARIADB_USER
        - name: MARIADB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "phpapp.fullname" . }}-secrets
              key: MARIADB_USER_PASSWORD
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ template "phpapp.fullname" . }}-secrets
              key: MARIADB_HOST
        - name: MARIADB_DB
          valueFrom:
            secretKeyRef:
              name: {{ template "phpapp.fullname" . }}-secrets
              key: MARIADB_DB
        ports:
        - name: mariadb
          containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            port: 80
            path: /healthz.html
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz.html
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
