{{- if .Values.maxscale.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "galera.fullname" . }}-{{ .Values.maxscale.masterOnlyService.name }}
  labels:
    app.kubernetes.io/name: {{ include "galera.name" . }}
    helm.sh/chart: {{ include "galera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.maxscale.masterOnlyService.type }}
  ports:
    - name: {{ .Values.maxscale.masterOnlyService.name }}
      port: {{ .Values.maxscale.masterOnlyService.port }}
      targetPort: {{ .Values.maxscale.masterOnlyService.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "galera.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-maxscale
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "galera.fullname" . }}-{{ .Values.maxscale.rwService.name }}
  labels:
    app.kubernetes.io/name: {{ include "galera.name" . }}
    helm.sh/chart: {{ include "galera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.maxscale.rwService.type }}
  ports:
    - name: {{ .Values.maxscale.rwService.name }}
      port: {{ .Values.maxscale.rwService.port }}
      targetPort: {{ .Values.maxscale.rwService.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "galera.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-maxscale
{{- end }}
