{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "galera.serviceAccountName" . }}
  labels:
{{ include "galera.labels" . | nindent 4 }}
{{- end -}}
